#!/bin/bash

> ~/CRC/exprData

echo "-------------------------------"
echo -e "    Colorectal Cancer Test\n"
echo -e "           based on\n"
echo -e "    Diagnostic Biomarkers"
echo "-------------------------------" 

# Read the expression of biomarkers
echo "Enter 'CDC25B' gene expression: "
read CDC25B
echo $CDC25B >> ~/CRC/exprData

echo "Enter 'CDK4' gene expression: "
read CDK4
echo $CDK4 >> ~/CRC/exprData

echo "Enter 'MMP1' gene expression: "
read MMP1
echo $MMP1 >> ~/CRC/exprData

echo "Enter 'MMP7' gene expression: "
read MMP7
echo $MMP7 >> ~/CRC/exprData

echo "Enter 'PLAU' gene expression: "
read PLAU
echo $PLAU >> ~/CRC/exprData 

echo "Enter 'SLC7A5' gene expression: "
read SLC7A5
echo $SLC7A5 >> ~/CRC/exprData

echo "Enter 'TEAD4' gene expression: "
read TEAD4
echo $TEAD4 >> ~/CRC/exprData

echo "Enter 'TRIB3' gene expression: "
read TRIB3
echo $TRIB3 >> ~/CRC/exprData

Rscript ~/CRC/RF.R